image: haskell:latest

before_script:
  - mkdir -p /root/stack
  - export STACK_ROOT=$(pwd)/.stack
  # - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  # - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" | sudo tee -a /etc/apt/sources.list
  - apt clean
  - apt update
  - apt install -y llvm-8-dev llvm-8-tools xz-utils make curl libgmp-dev llvm-6.0-dev llvm-6.0-tools
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH

stages:
  - build
  - test

buildSpicy:
  stage: build
  cache:
    paths:
      - .stack
      - $HOME/.stack
      - $HOME/.ghc
      - $HOME/.cabal
  script:
    - stack --no-terminal --install-ghc build --only-dependencies

testSpicy:
  stage: test
  cache:
    paths:
      - .stack
      - $HOME/.stack
      - $HOME/.ghc
      - $HOME/.cabal
  script:
    - stack --no-terminal test
