name:                spicy
version:             0.0.0.1
github:              "sheepforce/Spicy"
license:             GPL-3
author:              "Phillip Seeber"
maintainer:          "phillip.seeber@uni-jena.de"
copyright:           "2019 Phillip Seeber"

extra-source-files:
  - README.md
  - LICENSE
  - goldentests/input/*
  - goldentests/output/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sheepforce/Spicy#readme>

dependencies:
  - base >= 4.7 && <5
  - hmatrix >= 0.18.0.0
  - containers >= 0.5.7.1
  - microlens-platform >= 0.3.9.0
  - attoparsec >= 0.13.1.0
  - text >= 1.2.2.0
  - process >= 1.4.3.0
  - split >= 0.2.3.2
  - deepseq >= 1.4.2.0
  - parallel >= 3.2.1.0
  - random >= 1.1
  - filepath >= 1.4.2
  - utf8-string >= 1.0.1
  - bytestring >= 0.10.8
  - vector >= 0.12.0.2
  - array >= 0.5.2.0
  - repa >= 3.4.1.4

ghc-options:
  - -optP-Wno-nonportable-include-path
  - -O2
  - -Wall
  - -Wno-unused-matches
  - -Wno-unused-top-binds
  - -Wno-type-defaults

library:
  source-dirs: src

executables:
  spicy:
    main: spicy.hs
    source-dirs: app
    dependencies:
      - spicy
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -qa"
  benchmarks-exe:
    main: benchmarks.hs
    source-dirs: app
    dependencies:
      - spicy
      - criterion >= 1.4.1.0
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -qa"
  unittests-exe:
    main: testing.hs
    source-dirs: app
    dependencies:
      - spicy
      - tasty >= 0.11.3
      - tasty-hunit -any
      - tasty-golden >= 2.3.1
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -qa"

tests:
  unittests:
    main: testing.hs
    source-dirs: app
    dependencies:
      - spicy
      - tasty >= 0.11.3
      - tasty-hunit -any
      - tasty-golden >= 2.3.1
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N1 -qa"

benchmarks:
  benchmarks:
    main: benchmarks.hs
    source-dirs: app
    dependencies:
      - spicy
      - criterion >= 1.4.1.0
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N1 -qa"
